name: "herald tester"

on:
  workflow_run:
    workflows: ["test-trigger"]

jobs:
  happen:
    name: happen
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{github.event.workflow_run}}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          WORKFLOW_RUN_EVENT: $github.event.workflow_run.event
          WORKFLOW_RUN: $github.event.workflow_run
